#!/bin/bash

#########################################################
# Void Linux Install Script
#
# This script is intended to automate the install process
# and setup configuration of Void Linux.
#
# Created March 6th, 2020 by nerditup
#########################################################

#########################################################
# Configuration Variables
#########################################################

virtualbox='false';  # Setup the VirtualBox Guest Additions
debug='false';       # Require user input to proceed

# Hardware
disk='nvme0n1';
partition='p';
network='wlp58s0';
rootfs='xfs';

# Locale
region='CA';
country='Canada';
zone='Eastern';
locale='en_'"$region"'.UTF-8';

# Personal
hostname='VoidBox';
password='testpass';
username='nerditup';

# Repository URL
repo_url='https://mirror.clarkson.edu/voidlinux/current/musl'

#########################################################
# Useful Functions
#########################################################

# Partition the Hard Disk
partition_disk() {
    # Boot Partition
    parted -s /dev/"$disk" mklabel gpt;
    parted -s /dev/"$disk" mkpart primary 1MiB 513MiB;
    parted -s /dev/"$disk" set 1 esp on;

    # Root Partition
    parted -s /dev/"$disk" mkpart primary 513MiB 100%;
}

# Format the Hard Disk
format_disk() {
    # Boot Partition
    mkfs.fat -F 32 /dev/"$disk""$partition"1;

    # Root Partition
    mkfs."$rootfs" /dev/"$disk""$partition"2;
}

# Mount the Partitions
mount_partitions() {
    # Root Partition
    mount /dev/"$disk""$partition"2 /mnt;

    # Boot Partition
    mkdir /mnt/boot;  # Create a boot directory to mount to.
    mount /dev/"$disk""$partition"1 /mnt/boot;

    mkdir /mnt/dev /mnt/proc /mnt/sys
    mount --rbind /dev /mnt/dev
    mount --rbind /proc /mnt/proc
    mount --rbind /sys /mnt/sys

    # Ensure the following directory structure exists:
    # /boot/EFI/BOOT/foo.efi
    # /boot/{vmlinuz-linux, initramfs-linux.img}
    #
    # EFI entries won't show up in the firmware if no file exists in esp/EFI/BOOT/foo.efi
}

# Configure the fstab File
configure_fstab() {
    # TODO: this.
}

# Configure the Timezone
configure_timezone() {
    # TODO: this.
}

# Configure the NTP
configure_ntp() {
    # TODO: this.
}

# Configure the Hostname
configure_hostname() {
    echo "$hostname" > /mnt/etc/hostname;
}

# Configure the Network
configure_network() {
    # TODO: this.
}

# Configure the Non-Root User
configure_user() {
    # TODO: this.
    #arch-chroot /mnt useradd -m -g users -G wheel -s /bin/bash $username;
    #(echo "$password"; echo "$password";) | arch-chroot /mnt passwd $username;
}

# Configure the Bootloader
configure_bootloader() {
    # TODO: this.
}

# Set the Root Password
set_root_password() {
    # TODO: this.
}

#########################################################
# Installation Procedure
#########################################################

# Disk Setup
partition_disk     # Partition the Hard Disk
format_disk        # Format the Hard Disk
mount_partitions   # Mount the Partitions

# Install Packages
export XBPS_ARCH=x86_64-musl
xbps-install -S -R "${repo_url}" -r /mnt base-system grub-x86_64-efi

# Configure the System
configure_fstab         # Configure the fstab File
